/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as MainProjectsRouteImport } from './routes/_main/projects'
import { Route as MainProjectsIdIndexRouteImport } from './routes/_main/projects/$id.index'
import { Route as MainProjectsIdProspectsRouteImport } from './routes/_main/projects/$id.prospects'
import { ServerRoute as ApiWaitlistServerRouteImport } from './routes/api/waitlist'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth.$'

const rootServerRouteImport = createServerRootRoute()

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsIdIndexRoute = MainProjectsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => MainProjectsRoute,
} as any)
const MainProjectsIdProspectsRoute = MainProjectsIdProspectsRouteImport.update({
  id: '/$id/prospects',
  path: '/$id/prospects',
  getParentRoute: () => MainProjectsRoute,
} as any)
const ApiWaitlistServerRoute = ApiWaitlistServerRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sign-up': typeof SignUpRoute
  '/projects': typeof MainProjectsRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/': typeof MainIndexRoute
  '/projects/$id/prospects': typeof MainProjectsIdProspectsRoute
  '/projects/$id': typeof MainProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-up': typeof SignUpRoute
  '/projects': typeof MainProjectsRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/': typeof MainIndexRoute
  '/projects/$id/prospects': typeof MainProjectsIdProspectsRoute
  '/projects/$id': typeof MainProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/sign-up': typeof SignUpRoute
  '/_main/projects': typeof MainProjectsRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/_main/': typeof MainIndexRoute
  '/_main/projects/$id/prospects': typeof MainProjectsIdProspectsRoute
  '/_main/projects/$id/': typeof MainProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-up'
    | '/projects'
    | '/projects/new'
    | '/'
    | '/projects/$id/prospects'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-up'
    | '/projects'
    | '/projects/new'
    | '/'
    | '/projects/$id/prospects'
    | '/projects/$id'
  id:
    | '__root__'
    | '/_main'
    | '/sign-up'
    | '/_main/projects'
    | '/projects/new'
    | '/_main/'
    | '/_main/projects/$id/prospects'
    | '/_main/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  SignUpRoute: typeof SignUpRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/waitlist': typeof ApiWaitlistServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/waitlist': typeof ApiWaitlistServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/waitlist': typeof ApiWaitlistServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/waitlist' | '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/waitlist' | '/api/auth/$'
  id: '__root__' | '/api/waitlist' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiWaitlistServerRoute: typeof ApiWaitlistServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/projects': {
      id: '/_main/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects/$id/': {
      id: '/_main/projects/$id/'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof MainProjectsIdIndexRouteImport
      parentRoute: typeof MainProjectsRoute
    }
    '/_main/projects/$id/prospects': {
      id: '/_main/projects/$id/prospects'
      path: '/$id/prospects'
      fullPath: '/projects/$id/prospects'
      preLoaderRoute: typeof MainProjectsIdProspectsRouteImport
      parentRoute: typeof MainProjectsRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface MainProjectsRouteChildren {
  MainProjectsIdProspectsRoute: typeof MainProjectsIdProspectsRoute
  MainProjectsIdIndexRoute: typeof MainProjectsIdIndexRoute
}

const MainProjectsRouteChildren: MainProjectsRouteChildren = {
  MainProjectsIdProspectsRoute: MainProjectsIdProspectsRoute,
  MainProjectsIdIndexRoute: MainProjectsIdIndexRoute,
}

const MainProjectsRouteWithChildren = MainProjectsRoute._addFileChildren(
  MainProjectsRouteChildren,
)

interface MainRouteChildren {
  MainProjectsRoute: typeof MainProjectsRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainProjectsRoute: MainProjectsRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  SignUpRoute: SignUpRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiWaitlistServerRoute: ApiWaitlistServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
